# Generated by Django 4.2.8 on 2025-02-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='jenis_kelamin',
        ),
    ]
